### PR TITLE
Change hb+jwt to kb+jwt and more holder to key

### PR DESCRIPTION
**Pull request by bc-pi**
Change hb+jwt to kb+jwt in anticipation of using the term Key Binding rather than Holder Binding per https://github.com/oauth-wg/oauth-selective-disclosure-jwt/issues/281

### CODE REVIEW

**Comment by bc-pi** [comment]
The proposed SD-JWT draft text changes are in PR https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/286

**Comment by bc-pi** [comment]
Also changed `holder_binding` to `key_binding` and `hb_` to `kb_` and `holder binding` to `key binding` throughout to try and have code, comments, and generated files reflect calling it key binding rather than holder binding

**Review by danielfett — APPROVED** [review]

**Comment by danielfett** [comment]
Looks good to me. We need to touch the examples in the two depending specs as well, so we need to coordinate that.

**Comment by danielfett** [comment]
@bc-pi I noticed that the `holder_binding` property is not described in the README.md and added it there. Can you please change the key's name in this PR as well?

**Comment by bc-pi** [comment]
> I noticed that the holder_binding property is not described in the README.md and added it there. Can you please change the key's name in this PR as well?

Yep, that's done now with c6fa07b8074ae991e813370740a36ed783efd1f8 and 9d049047d9e935b680e01bec001700a044012a67

**Comment by bc-pi** [comment]
> Looks good to me. We need to touch the examples in the two depending specs as well, so we need to coordinate that.

https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/286/files touches the examples in SD-JWT. I think last week you said you'd get SD-JWT VC updated after the fact.

**Pull request merged**
